(() => {
  const BAG='fashion_demo_bag_v1', WISH='fashion_demo_wishlist_v1';
  const get=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
  const put=(key,val)=>{try{localStorage.setItem(key,JSON.stringify(val))}catch{}};
  const updateCounts=()=>{const bag=get(BAG), wish=get(WISH);document.querySelectorAll('[data-bag-count]').forEach(e=>e.textContent=bag.reduce((n,p)=>n+(p.qty||1),0));document.querySelectorAll('[data-wish-count]').forEach(e=>e.textContent=wish.length)};
  document.querySelectorAll('.menu-toggle').forEach(btn=>btn.addEventListener('click',()=>{const nav=document.querySelector('.main-nav');const open=nav.classList.toggle('open');btn.setAttribute('aria-expanded',String(open))}));
  document.querySelectorAll('[data-size]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed','false'));btn.setAttribute('aria-pressed','true')}));
  document.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>{const item={id:btn.dataset.add,name:btn.dataset.name||btn.dataset.add,price:Number(btn.dataset.price||0),size:document.querySelector('[data-size][aria-pressed=true]')?.dataset.size||'M',qty:1};const bag=get(BAG);const found=bag.find(p=>p.id===item.id&&p.size===item.size);if(found)found.qty++;else bag.push(item);put(BAG,bag);updateCounts();btn.textContent='ADDED TO BAG';setTimeout(()=>btn.textContent='ADD TO BAG',1100)}));
  document.querySelectorAll('[data-wish]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.wish;const list=get(WISH);const i=list.indexOf(id);if(i>=0){list.splice(i,1);btn.textContent='♡ WISHLIST'}else{list.push(id);btn.textContent='♥ SAVED'}put(WISH,list);updateCounts()}));
  const search=document.querySelector('[data-search]'); if(search){const rows=[...document.querySelectorAll('[data-search-item]')];search.addEventListener('input',()=>{const q=search.value.toLowerCase();rows.forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))})}
  document.querySelectorAll('[data-accordion]').forEach(btn=>btn.addEventListener('click',()=>{const panel=btn.nextElementSibling;const hidden=panel.hasAttribute('hidden');panel.toggleAttribute('hidden',!hidden);btn.setAttribute('aria-expanded',String(hidden))}));
  const cart=document.querySelector('[data-cart]');if(cart){const bag=get(BAG);if(!bag.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='Your bag is clear. Explore the latest cut.';cart.append(empty)}else{let total=0;const table=document.createElement('table');table.className='cart-table';const head=table.createTHead().insertRow();['Item','Size','Qty','Price'].forEach(label=>{const th=document.createElement('th');th.textContent=label;head.append(th)});const body=table.createTBody();bag.forEach(item=>{total+=(Number(item.price)||0)*(Number(item.qty)||1);const row=body.insertRow();[item.name,item.size,String(item.qty||1),'€'+String(item.price||0)].forEach(value=>{const cell=row.insertCell();cell.textContent=value})});const foot=table.createTFoot().insertRow();const label=foot.insertCell();label.colSpan=3;label.textContent='Subtotal';const sum=foot.insertCell();sum.textContent='€'+String(total);cart.append(table);const clear=document.createElement('button');clear.className='btn btn-dark';clear.type='button';clear.textContent='Clear demo bag';clear.addEventListener('click',()=>{put(BAG,[]);location.reload()});cart.append(clear)}}
  updateCounts();
})();
